FLASK_APP='app.py'
FLASK_ENV=development
SECRET_KEY='you-will-never-guess'
DB_USERNAME=sa
DB_PASSWORD=T@st1234
DB_HOST=192.168.17.89
DATABASE_NAME=ref_web
MYSQL_ROOT_PASSWORD=rootpass
BLOG_NAME='Reference Data'
BLOG_POST_IMAGES_PATH='D:/Python/Code/flogger-master/static/images/uploads'
