"""empty message

Revision ID: c4ecc2bdd866
Revises: 36541d6984f3
Create Date: 2019-05-16 14:53:39.473257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ecc2bdd866'
down_revision = '36541d6984f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CATMTable',
    sa.Column('CATM_UKEY', sa.Integer(), nullable=False),
    sa.Column('CC', sa.String(length=2), nullable=True),
    sa.Column('Changwat_TH', sa.String(length=255), nullable=True),
    sa.Column('Changwat_EN', sa.String(length=255), nullable=True),
    sa.Column('AA', sa.String(length=2), nullable=True),
    sa.Column('Ampur_TH', sa.String(length=255), nullable=True),
    sa.Column('Ampur_EN', sa.String(length=255), nullable=True),
    sa.Column('TT', sa.String(length=2), nullable=True),
    sa.Column('Tumbon_TH', sa.String(length=255), nullable=True),
    sa.Column('Tumbon_EN', sa.String(length=255), nullable=True),
    sa.Column('MM', sa.String(length=2), nullable=True),
    sa.Column('CATM_TDATE', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('CATM_UKEY')
    )
    op.drop_table('ChngwatTable')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.create_table('ChngwatTable',
    sa.Column('CATM_UKEY', sa.INTEGER(), server_default=sa.text('nextval(\'"ChngwatTable_CATM_UKEY_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('CC', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('Changwat_TH', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Changwat_EN', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('AA', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('Ampur_TH', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Ampur_EN', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('TT', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('Tumbon_TH', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Tumbon_EN', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('MM', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('CATM_TDATE', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CATM_UKEY', name='ChngwatTable_pkey')
    )
    op.drop_table('CATMTable')
    # ### end Alembic commands ###
