"""empty message

Revision ID: 48d6492995d2
Revises: cd5d37b71e2e
Create Date: 2019-06-14 16:36:56.616679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d6492995d2'
down_revision = 'cd5d37b71e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goverment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gov_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goverment')
    # ### end Alembic commands ###
