"""empty message

Revision ID: 9ca5591ba684
Revises: e45529102538
Create Date: 2019-06-17 12:54:23.712375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca5591ba684'
down_revision = 'e45529102538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goverment', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('goverment', 'gov_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goverment', sa.Column('gov_name', sa.VARCHAR(length=50, collation='Thai_100_CI_AI'), autoincrement=False, nullable=True))
    op.drop_column('goverment', 'name')
    # ### end Alembic commands ###
