"""empty message

Revision ID: d260991d1515
Revises: eeb1aad5a2de
Create Date: 2019-06-23 12:34:43.004022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd260991d1515'
down_revision = 'eeb1aad5a2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('api_request', sa.String(length=255), nullable=True))
    op.add_column('post', sa.Column('api_response', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'api_response')
    op.drop_column('post', 'api_request')
    # ### end Alembic commands ###
