"""empty message

Revision ID: eeb1aad5a2de
Revises: 9ca5591ba684
Create Date: 2019-06-20 15:03:21.271189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb1aad5a2de'
down_revision = '9ca5591ba684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('api_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'api_url')
    # ### end Alembic commands ###
